### ISSUE TITLE
Why loading only for login shells?

### ISSUE THREAD

**Issue by endorama** [tomyun/base16-fish#6]
Hello, I started using this plugin and I noticed that the theme was not persisted across terminal restart.

It is caused by the `status --is-login` check, which in my case is always false. I'm on elementary Hera.

The check has been introduced with this commit https://github.com/tomyun/base16-fish/commit/2a99033eb857ac0e4c3c5beff3efdc359d17ffc2.

My workaround has been adding 

```
if test -n "$base16_theme"
  base16-$base16_theme
end
```

in my `config.fish`, and I'm wondering why that changed has been introduced, as in my case it seems it broke the integration.

Thanks for the plugin and your help!

**Comment by tomyun** [comment]
It had to be changed as described in #2. There were some cases where fish was running embedded in another program, not in terminal, and string output with escape codes caused an issue. How about using `--is-interactive` instead of `--is-login` in your case?

**Comment by endorama** [comment]
I tried with `status --is-interactive` and it seems is working fine!

Is it worth a PR? happy to provide one

**Comment by tomyun** [comment]
Just committed the change. Thanks for reporting back!
